"""empty message

Revision ID: 84aed92dd99c
Revises: ad0d81f7800e
Create Date: 2017-11-13 22:53:50.351031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84aed92dd99c'
down_revision = 'ad0d81f7800e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###
