"""empty message

Revision ID: b8f4ed13f70e
Revises: a6e4a009ce22
Create Date: 2017-11-11 21:15:03.814456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f4ed13f70e'
down_revision = 'a6e4a009ce22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('next_index', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('prev_index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chapters_index'), 'chapters', ['index'], unique=True)
    op.drop_index('index', table_name='chapters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index', 'chapters', ['index'], unique=True)
    op.drop_index(op.f('ix_chapters_index'), table_name='chapters')
    op.drop_column('chapters', 'prev_index')
    op.drop_column('chapters', 'next_index')
    # ### end Alembic commands ###
