"""empty message

Revision ID: be42a074a67c
Revises: b8f4ed13f70e
Create Date: 2017-11-11 23:12:27.456329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be42a074a67c'
down_revision = 'b8f4ed13f70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapters_index', table_name='chapters')
    op.create_index(op.f('ix_chapters_index'), 'chapters', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_index'), table_name='chapters')
    op.create_index('ix_chapters_index', 'chapters', ['index'], unique=True)
    # ### end Alembic commands ###
